# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMusicstreamer():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:8080/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_musicstreamer(self):
    # Test name: musicstreamer
    # Step # | name | target | value | comment
    # 1 | open | https://twitter.com/Bullishbeats/status/1515476924902088706 |  | 
    self.driver.get("https://twitter.com/Bullishbeats/status/1515476924902088706")
    # 2 | click | css=.css-4rbku5 > .css-1dbjc4n > .r-1p0dtai .css-9pa8cd |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-4rbku5 > .css-1dbjc4n > .r-1p0dtai .css-9pa8cd").click()
    # 3 | waitForElementNotPresent | css=.play-button--standard | 30000 | 
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, ".play-button--standard")))
    # 6 | click | xpath=//*[@id="scrollable-page"]/main/div/div[1]/div/div/div[2]/div/div/button |  | 
    self.driver.find_element(By.XPATH, "//*[@id=\"scrollable-page\"]/main/div/div[1]/div/div/div[2]/div/div/button").click()
    # 7 | click | css=.chrome-player | //*[@id="scrollable-page"]/div/div/amp-chrome-player//div/div[1]/apple-music-playback-controls//div/div[3]/amp-playback-controls-repeat//button/amp-icon | 
    self.driver.find_element(By.CSS_SELECTOR, ".chrome-player").click()
  
